[build]
builder = "nixpacks"
buildCommand = "git clone https://github.com/PolicyEngine/policyengine-us.git policyengine-us 2>/dev/null || true && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python api.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10