[build]
builder = "nixpacks"
buildCommand = "git submodule update --init --recursive && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python api.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10